// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiscoverProjects(arg1, arg2) {
  return window['go']['main']['App']['DiscoverProjects'](arg1, arg2);
}

export function StorePath() {
  return window['go']['main']['App']['StorePath']();
}
