// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeRepository(arg1) {
  return window['go']['main']['App']['AnalyzeRepository'](arg1);
}

export function AskRepositoryQuestion(arg1) {
  return window['go']['main']['App']['AskRepositoryQuestion'](arg1);
}

export function DiscoverProjects(arg1) {
  return window['go']['main']['App']['DiscoverProjects'](arg1);
}

export function GetResearchSession(arg1) {
  return window['go']['main']['App']['GetResearchSession'](arg1);
}

export function ListResearchSessions(arg1) {
  return window['go']['main']['App']['ListResearchSessions'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function SettingsStatus() {
  return window['go']['main']['App']['SettingsStatus']();
}

export function StorePath() {
  return window['go']['main']['App']['StorePath']();
}

export function TestGitHubConnection() {
  return window['go']['main']['App']['TestGitHubConnection']();
}

export function TestLLMConnection(arg1) {
  return window['go']['main']['App']['TestLLMConnection'](arg1);
}

export function TestLLMConnectionDraft(arg1) {
  return window['go']['main']['App']['TestLLMConnectionDraft'](arg1);
}
