// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {config} from '../models';

export function DiscoverProjects(arg1:string,arg2:number):Promise<domain.DiscoveryResult>;

export function SettingsStatus():Promise<config.SettingsStatus>;

export function StorePath():Promise<string>;
